name: scip-go
'on':
  push:
    paths:
      - '**.go'
jobs:
  scip-go:
    if: github.repository == 'sourcegraph/log'
    runs-on: ubuntu-latest
    container: sourcegraph/scip-go
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get src-cli
        run: curl -L https://sourcegraph.com/.api/src-cli/src_linux_amd64 -o /usr/local/bin/src;
          chmod +x /usr/local/bin/src
      - name: Set directory to safe for git
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Run scip-go
        working-directory: ''
        run: scip-go --no-animation

      - name: Upload SCIP to Cloud
        run: src code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
        env:
          SRC_ENDPOINT: https://sourcegraph.com/
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN_DOTCOM }}

      - name: Upload SCIP to S2
        run: src code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
        env:
          SRC_ENDPOINT: https://sourcegraph.sourcegraph.com/
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN_S2 }}
          
      - name: Upload SCIP to Demo
        run: src code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress || true
        env:
          SRC_ENDPOINT: https://demo.sourcegraph.com/
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN_DEMO }}
